USE EduFlowAIDB


CREATE TABLE USERS(
USERID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
USERIDENTIFIER VARCHAR(32) NOT NULL,
USERNAME VARCHAR(50),
EMAILID VARCHAR(100) NOT NULL,
PASSWORDHASH VARCHAR(256),
FIRSTNAME VARCHAR(50),
LASTNAME VARCHAR(50),
PROFILEPICTUREPATH VARCHAR(500),
USERTIMEZONE VARCHAR(50),
CREATEDAT DATETIME NOT NULL,
UPDATEDAT DATETIME,
ISACTIVE BIT NOT NULL DEFAULT 1, 
PASSWORDRESETTOKEN VARCHAR(100),
PASSWORDRESETTOKENEXPIRY DATETIME,
AUTUHPROVIDER VARCHAR(50),
EMAILVERIFIED BIT,
LASTLOGINAT DATETIME,
GOOGLEID VARCHAR(100)
);


CREATE TABLE EMAILVERIFICATIONS(
EMAILTOKENID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
USERID INT NOT NULL,
TOKEN VARCHAR(100) NOT NULL,
EXPIRESAT DATETIME NOT NULL,
ISUSED BIT,
CREATEDAT DATETIME

CONSTRAINT FK_EMAILVERIFICATIONS_USERS FOREIGN KEY (USERID) 
REFERENCES dbo.USERS(USERID)
);


CREATE TABLE REFRESHTOKENS(
REFRESHTOKENID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
REFRESHTOKEN VARCHAR(32) NOT NULL,
REFRESHEXPIRY DATETIME ,
ISREVOKED BIT, 
USERID INT NOT NULL,
CREATEDAT DATETIME 

CONSTRAINT FK_REFRESHTOKENS_USERS FOREIGN KEY (USERID)
REFERENCES dbo.USERS(USERID)
);

CREATE TABLE STATUSMASTER(
STATUSID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
STATUSIDENTIFIER VARCHAR(32) NOT NULL, 
STATUS VARCHAR(50) NOT NULL,
CREATEDAT DATETIME NOT NULL, 
UPDATEAT DATETIME,
CREATEDBY INT,
UPDATEDBY INT ,

CONSTRAINT FK_STATUSMASTER_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_STATUSMASTER_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID)
);


CREATE TABLE PRIORITYMASTER(
PRIORITYID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
PRIORITYIDENTIFIER VARCHAR(32) NOT NULL,
PRIORITY VARCHAR(50) NOT NULL, 
CREATEDAT DATETIME NOT NULL,
UPDATEDAT DATETIME,
CREATEDBY INT, 
UPDATEDBY INT, 

CONSTRAINT FK_PRIORITYMASTER_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_PRIORITYMASTER_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID)
);

CREATE TABLE GOALTYPEMASTER(
GOALTYPEID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
GOALTYPEIDENTIFIER VARCHAR(32) NOT NULL,
GOALTYPE VARCHAR(50) NOT NULL,
CREATEDAT DATETIME, 
UPDATEDAT DATETIME,
CREATEDBY INT,
UPDATEDBY INT 

CONSTRAINT FK_GOALTYPEMASTER_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_GOALTYPEMASTER_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID)
);


CREATE TABLE USERAVAILABILITY(
AVAILABILITYID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
USERID INT NOT NULL,
AVAILABLEHOURS DECIMAL(5,2) NOT NULL,
CREATEDAT DATETIME NOT NULL,
UPDATEDAT DATETIME,
DAYOFWEEK VARCHAR(20) NOT NULL,
ISENABLE BIT NOT NULL DEFAULT 1,
CREATEDBY INT, 
UPDATEDBY INT,

CONSTRAINT FK_USERAVAILABILITY_USERS_USERID FOREIGN KEY (USERID)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_USERAVAILABILITY_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_USERAVAILABILITY_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID)
);	

CREATE TABLE NOTIFICATIONS(
NOTIFICATIONID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
NOTIFICATIONIDENTIFIER VARCHAR(32) NOT NULL,
NOTIFICATION VARCHAR(100) NOT NULL,
CREATEDAT DATETIME NOT NULL,
UPDATEAT DATETIME,
CREATEDBY INT, 
UPDATEDBY INT

CONSTRAINT FK_NOTIFICATIONS_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_NOTIFICATIONS_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID)
);

CREATE TABLE GOALMANAGEMENT(
GOALID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
GOALIDENTIFIER VARCHAR(32) NOT NULL,
GOALTITLE VARCHAR(100) NOT NULL,
GOALDESCRIPTION VARCHAR(500),
GOALTYPEID INT NOT NULL,
TARGETDATE DATETIME NOT NULL,
PRIORITYTYPEID INT NOT NULL,
STATUSID INT,
CREATEDAT DATETIME NOT NULL,
CREATEDBY INT NOT NULL,
UPDATEDAT DATETIME,
UPDATEDBY INT,
USERID INT NOT NULL,

CONSTRAINT FK_GOALMANAGEMENT_GOALTYPEMASTER FOREIGN KEY (GOALTYPEID)
REFERENCES dbo.GOALTYPEMASTER(GOALTYPEID),

CONSTRAINT FK_GOALMANAGEMENT_PRIORITYMASTER FOREIGN KEY (PRIORITYTYPEID)
REFERENCES dbo.PRIORITYMASTER(PRIORITYID),

CONSTRAINT FK_GOALMANAGEMENT_STATUSMASTER FOREIGN KEY (STATUSID)
REFERENCES dbo.STATUSMASTER(STATUSID),

CONSTRAINT FK_GOALMANAGEMENT_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_GOALMANAGEMENT_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID),

);

CREATE TABLE TASKMANAGEMENT(
TASKID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TASKIDENTIFIER VARCHAR(32) NOT NULL,
TASKNAME VARCHAR(100) NOT NULL,
GOALID INT NOT NULL,
TASKDESCRIPTION VARCHAR(500),
DUEDATE DATETIME NOT NULL,
ISAIGENERATED BIT NOT NULL DEFAULT 0,
STATUSID INT, 
CREATEDBY INT NOT NULL,
UPDATEDBY INT,
CREATEDAT DATETIME NOT NULL,
UPDATEDAT DATETIME,

CONSTRAINT FK_TASKMANAGEMENT_GOALMANAGEMENT FOREIGN KEY (GOALID)
REFERENCES dbo.GOALMANAGEMENT(GOALID),

CONSTRAINT FK_TASKMANAGEMENT_STATUSMASTER FOREIGN KEY (STATUSID)
REFERENCES dbo.STATUSMASTER(STATUSID),

CONSTRAINT FK_TASKMANAGEMENT_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_TASKMANAGEMENT_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID)
);


CREATE TABLE SCHEDULEMANAGEMENT(
SCHEDULEID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
SCHEDULEIDENTIFIER VARCHAR(32) NOT NULL,
TASKID INT NOT NULL,
GOALID INT NOT NULL,
SCHEDULEDDATE DATETIME NOT NULL,
PLANNEDHOURS DECIMAL(5,2) NOT NULL,
STATUSID INT,
CREATEDBY INT NOT NULL,
CREATEDAT DATETIME NOT NULL,
UPDATEDBY INT,
UPDATEDAT DATETIME,

CONSTRAINT FK_SCHEDULEMANAGEMENT_TASKMANAGEMENT FOREIGN KEY (TASKID)
REFERENCES dbo.TASKMANAGEMENT(TASKID),

CONSTRAINT FK_SCHEDULEMANAGEMENT_GOALMANAGEMENT FOREIGN KEY (GOALID)
REFERENCES dbo.GOALMANAGEMENT(GOALID),

CONSTRAINT FK_SCHEDULEMANAGEMENT_STATUSMASTER FOREIGN KEY (STATUSID)
REFERENCES dbo.STATUSMASTER(STATUSID),

CONSTRAINT FK_SCHEDULEMANAGEMENT_USERS_CREATEDBY FOREIGN KEY (CREATEDBY)
REFERENCES dbo.USERS(USERID),

CONSTRAINT FK_SCHEDULEMANAGEMENT_USERS_UPDATEDBY FOREIGN KEY (UPDATEDBY)
REFERENCES dbo.USERS(USERID)
);


